vich_uploader:
    db_driver: orm

    mappings:
        advisors_cv:
            uri_prefix: uploads/advisors/cv
            upload_destination: '%upload_advisors_cv_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        enterprises_brochure:
            uri_prefix: uploads/enterprises/brochure
            upload_destination: '%upload_enterprises_brochure_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
