vich_uploader:
    db_driver: orm

    mappings:
        user_file:
            uri_prefix: uploads/images/users
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
