language: php
php:
    - '7.4'

before_install:
    - if [ -d "./.idea" ]; then echo "Forbidden idea folder found ! Please, ignore them globaly..."; exit 2; fi
    - if [ -d "./.vscode" ]; then echo "Forbidden vscode folder found ! Please, ignore them globaly..."; exit 2; fi
    - if [ -d "./.env.local" ]; then echo "Forbidden configuration file found !"; exit 2; fi
    - if [ -d "./vendor" ]; then echo "Forbidden external libs folder found !"; exit 2; fi
    - if [ $(find ./ -name .DS_Store) ]; then echo "Forbidden MacOS boring file found ! Please, ignore them globaly..."; exit 2; fi
    - sudo apt install zlib1g-dev
    - sudo apt install libgnutls28-dev
    - sudo apt install libgnutls-dev
    - sudo apt install libssl-dev
    - printf "\n" | pecl install imagick
    - printf "\n" | pecl install pecl_http

install:
    - composer install
    - yarn --ignore-engines install
script:
    - ./bin/phpcs
    - ./bin/phpstan analyse src --level max
    - ./bin/phpmd src text phpmd.xml
    - ./bin/eslint assets/js
    - ./bin/sass-lint -c sass-linter.yml -v
notifications:
    email:
        - actix2013@gmail.com
        - amina.aitm@gmail.com
        - cvr.contact.pro@gmail.com
        - raphael.morales@hotmail.fr
        - benjamin.moniotte@gmail.com
        - r.moulet0@gmail.com
branches:
    only:
        - master
        - dev
